# Generated by Django 3.2.22 on 2023-10-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('image_resource', models.URLField()),
                ('move_priority', models.PositiveIntegerField()),
                ('starting_coordinate', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
    ]
