# Generated by Django 3.2.22 on 2023-10-21 18:30

from django.db import migrations, models
from clue_game_api.characters.models import Character
from dataclasses import dataclass


@dataclass
class ClueGameCharacter:
    name: str
    move_priority: int
    starting_coordinate: str


clue_game_characters = [
    ClueGameCharacter("Colonel Mustard", 2, "Lounge-DiningRoom-Hallway"),
    ClueGameCharacter("Miss Scarlet", 1, "Hall-Lounge-Hallway"),
    ClueGameCharacter("Mr. Green", 4, "Conservatory-BallRoom-Hallway"),
    ClueGameCharacter("Mrs. Peacock", 5, "Library-Conservatory-Hallway"),
    ClueGameCharacter("Mrs. White", 3, "BallRoom-Kitchen-Hallway"),
    ClueGameCharacter("Professor Plum", 6, "Study-Library-Hallway"),
]


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0001_initial"),
    ]

    def default_characters_insert(apps, schema_editor):
        for character in clue_game_characters:
            character_model = Character(name=character.name, move_priority=character.move_priority, starting_coordinate=character.starting_coordinate)
            character_model.save()

    operations = [
        migrations.RunPython(default_characters_insert),
    ]
