# Generated by Django 3.2.22 on 2023-10-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('passage_to_room', models.ForeignKey(help_text='The identifier of the room this room has a secret passage to.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.room')),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
