# Generated by Django 3.2.23 on 2023-11-13 23:13

import clue_game_api.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cards',
            field=models.JSONField(default=clue_game_api.users.models.cards_dict),
        ),
    ]
