# Generated by Django 3.2.23 on 2023-12-06 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hallways', '0002_hallways_init'),
        ('users', '0002_user_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hallway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hallways.hallways'),
        ),
    ]
