# Generated by Django 3.2.22 on 2023-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('weapon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image_resource', models.URLField()),
            ],
            options={
                'db_table': 'weapon',
            },
        ),
    ]
