# Generated by Django 3.2.22 on 2023-10-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("weapon", "0002_weapons_init")]

    operations = [migrations.RunSQL("DROP TABLE IF EXISTS weapons")]
