# Generated by Django 3.2.23 on 2023-11-08 01:47

import clue_game_api.game.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_characters_init'),
        ('room', '0002_characters_init'),
        ('weapon', '0003_remove_old_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                # ('id', models.UUIDField(default=clue_game_api.game.models.create_random_external_game_id, editable=False, unique=True)),
                ('join_code', models.CharField(default=clue_game_api.game.models.create_random_join_code, editable=False, max_length=20, unique=True)),
                ('solution_character_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('solution_room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('solution_weapon_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weapon.weapon')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
