# Generated by Django 3.2.23 on 2023-11-09 03:53

import clue_game_api.game.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_characters_init"),
        ("characters", "0002_characters_init"),
        ("weapon", "0003_remove_old_table"),
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="session_id",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="join_code",
            field=models.CharField(
                default=clue_game_api.game.models.create_random_join_code, editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="solution_character_id",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="characters.character"),
        ),
        migrations.AlterField(
            model_name="game",
            name="solution_room_id",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="room.room"),
        ),
        migrations.AlterField(
            model_name="game",
            name="solution_weapon_id",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="weapon.weapon"),
        ),
    ]
