# Generated by Django 3.2.23 on 2023-11-11 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20231109_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='external_game_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunSQL("ALTER TABLE game DROP COLUMN IF EXISTS id;")
    ]
