# Generated by Django 3.2.23 on 2023-11-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_external_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='solution_character_id',
            new_name='solution_character',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='solution_room_id',
            new_name='solution_room',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='solution_weapon_id',
            new_name='solution_weapon',
        ),
    ]
